apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflasktemplate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myflasktemplateimg
        image: koubelan/myflasktemplateimg:latest
        ports:
        - containerPort: 5000